services:
  db:
    image: postgres:16.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=dev_fileshare_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 60s
  
  rails:
    build: ./app
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres: